### ISSUE TITLE
Error with pulling docker images

### ISSUE THREAD

**Issue by zhujack8** [CCRGeneticsBranch/AWS_POC_MVP_NF#22]
I ran the pipeline from the shared folder (/data/GBNCI/projects/AWS_POC_MVP_NF_test), but got multiple docker image pulling errors, e.g. 

      FATAL:   While making image from oci registry: error fetching image to cache: while building SIF from layers: conveyor failed to get: no descriptor found for reference "sha256.56013da920e460f0b7022869e4121a551d10ecb046a7fa33ce9834d54bb04d01"

The full log file is at: 

    /data/GBNCI/projects/AWS_POC_MVP_NF_test/results.exome-rnaseq_test2/.nextflow.log

I checked your guys' tests at /data/khanlab2/NF_benchmarking already has all the docker images cached. I might have missed something or done something not right.

Thanks,

Jack

**Comment by vinegang** [comment]
@zhujack8 , I am unable to access the path you provided. It could be permissions or incorrect path. 

`ls: cannot access '/data/GBNCI/projects/AWS_POC_MVP_NF_test/results.exome-rnaseq_test2/.nextflow.log': No such file or directory`

**Comment by zhujack8** [comment]
BTW, the GitHub version of your pipeline seems different from your local version on Khanlab drive because it generated different errors.
